$("#yes").click(function(){
    $("#firstMove").show();
    $("#decision").hide();
});
$("#Start").click(function(){
    $("#firstMove").hide();
    $("#decision").hide();
    $("#theFight").show();
});
